### ISSUE TITLE
EHN: sample_weight

### ISSUE THREAD

**Issue by kingjr** [alexandrebarachant/pyRiemann#13]
While playing with your package with @dengemann, we realized that it'd be really great to add a `sample_weight` option to the classifiers similarly to http://scikit-learn.org/stable/auto_examples/svm/plot_weighted_samples.html.

What do you think?

**Comment by alexandrebarachant** [comment]
Indeed, this is a good idea.
I only have one "original" classifier, MDM, which is basically a k-means using a riemannian metric.
To take this into account, it is as simple as passing weights to the mean estimation.
This could be done in `pyriemann.utils.mean`

I think i tried this a long time ago, and it didn't cause any major issues. However, the riemannian mean is already pretty robust to artefact (because of the log in the metric) so it does not make a big difference for this specific case. Anyway, it could be used to put emphasis on a subset of point in the dataset, which is a good think.

This is a easy PR, you can open one if you want.

**Comment by dengemann** [comment]
@alexandrebarachant out of curiosity, how do in your experience the reimaniann classifiers play with severe class imbalance?

**Comment by alexandrebarachant** [comment]
The main classifier is a k-means, i.e, it estimates a centroid independently for each class and base it's decision on the nearest centroid (according to the riemannian metric). In this sense, it can deal with severly unbalanced classes without any problem. As long as you have enough point to correctly estimate the centroid, the class balance does not matter.

Then, when i go for more advanced classifier, i used the tangent space mapping (`TangentSpace`), which is an unsupervised transformer. Then, the problem of class unbalance is passed to the final classifier step.

**Comment by alexandrebarachant** [comment]
Hi guys,
I added the parameter for all the Mean estimation (all the metric) + MDM classifier.
Note sure it's relevant to add it elsewhere, but i will check the code.
