### ISSUE TITLE
Q? CSP transform without cov

### ISSUE THREAD

**Issue by kingjr** [alexandrebarachant/pyRiemann#34]
I'm trying to do a dimensionality reduction with CSP, but want to keep the time sample to then perform a search light eg.
```
make_pipeline(
    CSP(2),  # find spatial filters where covariance is most predictive
    Windower(size=50, step=50),  # chunk into time slices
    SearchLight(make_pipeline(Covariances(), TangentSpace(), Logistic()))  # for each slice decode from cov
```

Would it make sense? If so, is it possible to implement it with pyRiemann?

Thanks!

**Comment by alexandrebarachant** [comment]
Hum, i would suggest to use the MNE CSP (but i'm not sure it can return raw spatially filtered signal).
otherwise, would suggest to put the CSP just after the Covariance, and flip the switch `log=False` so it can return spatially filtered covariance instead of just the log-variance.

i would like to avoid modifying the CSP api

**Comment by kingjr** [comment]
Ok, thanks
